[package]
name = "schedule_overlay"
version = "0.1.1"
edition = "2024"

[dependencies]
slint = "1.15.0"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
slint-build = "1.15.0"
toml = "0.9.11"
