[package]
name = "schedule_overlay"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = "1.14.1"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"

[build-dependencies]
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.11"
